= Example RELP Server

Build with
[source, bash]
----
mvn clean package
----

Run with
[source, bash]
----
java -jar rlp_07.jar
----

Listens to plain server port 1601 by default and prints received events.

Port can be changed with "-Dport=1234" command-line argument.

TLS mode can be enabled with "-Dtls=true" command-line argument.

Custom server keystore can be supplied with "-DtlsKeystore=path/to/file.jks".

Custom server keystore password can be supplied with "-DtlsKeystorePassword=MyCustomPassword".

Logging level output can be managed with "-Dloglevel=INFO". You can read more about logging levels https://logging.apache.org/log4j/2.x/manual/customloglevels.html[here]

[source, bash]
----
java -Dlog4j.configurationFile=log4j2.xml -jar rlp_07.jar
----

== Running the container

You can run the prebuilt container by simply running:

`docker run -ti --rm ghcr.io/teragrep/rlp_07/app:latest`

The container respects the following environment variables

[cols]
|===
|Environment variable|Property equivalent

|RLP_07_PORT=1243
|-Dport=1234

|RLP_07_TLS=false
|-Dtls=false

|RLP_07_TLS_KEYSTORE=/keystore.jks
|-DtlsKeystore=/keystore.jks

|RLP_07_TLS_KEYSTOREPASSWORD=changeit
|-DtlsKeystorePassword=changeit

|RLP_07_LOGLEVEL=INFO
|-Dloglevel=INFO
|===

== Contributing
 
// Change the repository name in the issues link to match with your project's name
 
You can involve yourself with our project by https://github.com/teragrep/rlp_07/issues/new/choose[opening an issue] or submitting a pull request.
 
Contribution requirements:
 
. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).
 
Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].
 
=== Contributor License Agreement
 
Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.
 
You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories. 
