name: Upload Artifact as GitHub Release Attachment

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'

      - name: Prepare RPM GPG signing
        run: |
          sudo apt-get install expect pinentry-tty;
          printf "RPM_SIGNING_KEYNAME=%q\n" "$(echo "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}" | gpg --show-keys --with-colons | awk -F':' '/uid/{print $10}')" >> $GITHUB_ENV;
          echo "${{ secrets.RPM_SIGNING_PRIVATE_KEY }}" | gpg --batch --import;
          echo "%_gpg_sign_cmd_extra_args --pinentry-mode loopback --passphrase \"%{getenv:RPM_SIGNING_PASSPHRASE}\"" >> "${HOME}/.rpmmacros";

      - name: Build a jar and rpm for release
        run: mvn --batch-mode -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= clean package && cd rpm/ && mvn --batch-mode -Drevision=${{ github.event.release.tag_name }} -Dsha1= -Dchangelist= -f rpm.pom.xml package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RPM_SIGNING_KEYNAME: ${{ env.RPM_SIGNING_KEYNAME }}
          RPM_SIGNING_PASSPHRASE: ${{ secrets.RPM_SIGNING_PASSPHRASE }}

      - name: Attach rpm to release
        uses: softprops/action-gh-release@v2
        with:
          files: rpm/target/rpm/com.teragrep-rlp_07/RPMS/noarch/com.teragrep-rlp_07-*.noarch.rpm

      - name: Update pkg_01 releases repository
        uses: teragrep/dfg_01@3.3.0
        with:
          from_repository: "${{ github.repository }}"
          from_version: "${{ github.event.release.tag_name }}"
          to_repository: "${{ github.repository_owner }}/pkg_01"
          deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY }}
          files: rpm/target/rpm/com.teragrep-rlp_07/RPMS/noarch/com.teragrep-rlp_07-*.noarch.rpm
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
          repo_baseurl: "${{ vars.PKG_01_CENTRAL_BASEURL }}"
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
        if: ${{ env.has_deploy_key == 'true' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: 'Build Image'
        run: |
          docker buildx build --output type=docker --tag ghcr.io/${{ env.REPO_LC }}/app:${{ github.event.release.tag_name }} --tag ghcr.io/${{ env.REPO_LC }}/app:latest  .
          docker push ghcr.io/${{ env.REPO_LC }}/app --all-tags
